name: ragnarock

services:
  frontend:
    build:
      context: ../..
      dockerfile: docker/staging/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_AUTH_URL: ${NEXT_PUBLIC_AUTH_URL}
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    external: true
    name: ragnarock_default
